services:
  web:
    build: .
    ports:
      - "8181:3000"
    environment:
      - JWT_SECRET=/run/secrets/jwt_secret
    secrets:
      - jwt_secret

secrets:
  jwt_secret:
    file: ./jwt_secret.txt
